# 使用官方 Python 鏡像作為基礎image
FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

ENV MODULE_NAME="src.main"

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]